import React, { useState } from 'react';
import { Bot, Sparkles, AlertTriangle } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import { generateContentWithFallback } from "../lib/gemini";
import { formatCurrency } from '../lib/utils';
import ReactMarkdown from 'react-markdown';

export const AIAnalyzer = ({ data, selectedMonth, allCategories }: { data: any, selectedMonth: string, allCategories: any[] }) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const analyzeData = async () => {
    setIsAnalyzing(true);
    setError(null);
    try {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
         throw new Error("Gemini API key is missing");
      }
      const ai = new GoogleGenAI({ apiKey });

      const monthExpenses = data.transactions.filter((t: any) => t.type === 'expense' && t.date.startsWith(selectedMonth));
      const monthIncome = data.transactions.filter((t: any) => t.type === 'income' && t.date.startsWith(selectedMonth));
      
      const totalSpent = monthExpenses.reduce((sum: number, e: any) => sum + e.amount, 0);
      const totalIncome = monthIncome.reduce((sum: number, e: any) => sum + e.amount, 0);

      const categoryTotals: Record<string, number> = {};
      monthExpenses.forEach((e: any) => {
        categoryTotals[e.category] = (categoryTotals[e.category] || 0) + e.amount;
      });

      const categoryDetails = Object.entries(categoryTotals).map(([catId, amount]) => {
        const cat = allCategories.find(c => c.id === catId);
        return `${cat?.name || catId}: ${formatCurrency(amount)}`;
      }).join('\n');

      const prompt = `Analyze this financial data for the month of ${selectedMonth}. 
      Total Income: ${formatCurrency(totalIncome)}
      Total Spent: ${formatCurrency(totalSpent)}
      
      Spending by category:
      ${categoryDetails}
      
      Please provide a brief, insightful financial analysis. Give suggestions for savings, alert on high spendings if any, and offer simple actionable advice. Format the output clearly. (Keep it concise enough for mobile viewing).`;

      const response = await generateContentWithFallback(ai, prompt);

      setAnalysis(response.text || "No analysis generated.");
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to analyze data.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="bg-gradient-to-br from-primary/10 to-secondary-container/30 border border-primary/20 rounded-[24px] p-5 mb-4 shadow-sm relative overflow-hidden">
      <div className="absolute top-0 right-0 p-4 opacity-10">
        <Bot size={80} />
      </div>
      <div className="flex items-center gap-2 mb-3">
        <Sparkles size={20} className="text-primary" />
        <h3 className="text-lg font-semibold text-on-surface">AI Financial Analyzer</h3>
      </div>
      
      {!analysis && !isAnalyzing && (
        <p className="text-sm text-on-surface-variant mb-4 relative z-10">
          Let Google Gemini analyze your transactions and savings for this month, and give you actionable financial advice.
        </p>
      )}

      {isAnalyzing ? (
        <div className="py-8 flex flex-col items-center justify-center gap-3">
          <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
          <p className="text-sm font-medium text-primary animate-pulse">Gemini is analyzing your finances...</p>
        </div>
      ) : analysis ? (
        <div className="relative z-10">
          <div className="markdown-body prose prose-sm prose-p:leading-snug prose-li:my-0.5 text-sm text-on-surface bg-surface-container-lowest/80 backdrop-blur-sm p-4 rounded-xl border border-outline-variant/30 max-h-[300px] overflow-y-auto">
            <ReactMarkdown>{analysis}</ReactMarkdown>
          </div>
          <div className="flex items-start gap-1.5 mt-3 text-on-surface-variant/70 text-xs px-2">
            <AlertTriangle size={14} className="shrink-0 mt-0.5" />
            <p className="leading-tight">
              Disclaimer: AI Analyzer predictions and advice are generated by AI and may be inaccurate or inappropriate for your specific financial situation. Please consult a financial advisor for professional advice.
            </p>
          </div>
        </div>
      ) : null}

      {error && (
        <div className="text-sm text-error bg-error-container/50 p-3 rounded-xl mb-4 relative z-10">
          {error}
        </div>
      )}

      {(!analysis || error) && (
        <button
          onClick={analyzeData}
          disabled={isAnalyzing}
          className="w-full relative z-10 py-3.5 bg-primary text-on-primary rounded-xl font-medium shadow-sm hover:opacity-90 active:scale-[0.98] transition-all flex items-center justify-center gap-2"
        >
          <Bot size={18} />
          {error ? "Try Again" : "Analyze My Finances"}
        </button>
      )}
    </div>
  );
};
